// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdmcfflmmerpihuhwciy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbWNmZmxtbWVycGlodWh3Y2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDgzNDgsImV4cCI6MjA2MDM4NDM0OH0.Vh5spE_P3WCpSd4kjvLtd1l5hZLIcLLuKOp4c943bnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);